// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/order"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rechargeproduct"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks    []Hook
	mutation *OrderMutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *OrderUpdate) SetOrderNo(v string) *OrderUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableOrderNo(v *string) *OrderUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrderUpdate) SetUserID(v int64) *OrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableUserID(v *int64) *OrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *OrderUpdate) SetProductID(v int64) *OrderUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableProductID(v *int64) *OrderUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// ClearProductID clears the value of the "product_id" field.
func (_u *OrderUpdate) ClearProductID() *OrderUpdate {
	_u.mutation.ClearProductID()
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *OrderUpdate) SetProductName(v string) *OrderUpdate {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableProductName(v *string) *OrderUpdate {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *OrderUpdate) SetAmount(v float64) *OrderUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableAmount(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *OrderUpdate) AddAmount(v float64) *OrderUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBonusAmount sets the "bonus_amount" field.
func (_u *OrderUpdate) SetBonusAmount(v float64) *OrderUpdate {
	_u.mutation.ResetBonusAmount()
	_u.mutation.SetBonusAmount(v)
	return _u
}

// SetNillableBonusAmount sets the "bonus_amount" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableBonusAmount(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetBonusAmount(*v)
	}
	return _u
}

// AddBonusAmount adds value to the "bonus_amount" field.
func (_u *OrderUpdate) AddBonusAmount(v float64) *OrderUpdate {
	_u.mutation.AddBonusAmount(v)
	return _u
}

// SetActualAmount sets the "actual_amount" field.
func (_u *OrderUpdate) SetActualAmount(v float64) *OrderUpdate {
	_u.mutation.ResetActualAmount()
	_u.mutation.SetActualAmount(v)
	return _u
}

// SetNillableActualAmount sets the "actual_amount" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableActualAmount(v *float64) *OrderUpdate {
	if v != nil {
		_u.SetActualAmount(*v)
	}
	return _u
}

// AddActualAmount adds value to the "actual_amount" field.
func (_u *OrderUpdate) AddActualAmount(v float64) *OrderUpdate {
	_u.mutation.AddActualAmount(v)
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *OrderUpdate) SetPaymentMethod(v string) *OrderUpdate {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *OrderUpdate) SetNillablePaymentMethod(v *string) *OrderUpdate {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// SetPaymentGateway sets the "payment_gateway" field.
func (_u *OrderUpdate) SetPaymentGateway(v string) *OrderUpdate {
	_u.mutation.SetPaymentGateway(v)
	return _u
}

// SetNillablePaymentGateway sets the "payment_gateway" field if the given value is not nil.
func (_u *OrderUpdate) SetNillablePaymentGateway(v *string) *OrderUpdate {
	if v != nil {
		_u.SetPaymentGateway(*v)
	}
	return _u
}

// SetTradeNo sets the "trade_no" field.
func (_u *OrderUpdate) SetTradeNo(v string) *OrderUpdate {
	_u.mutation.SetTradeNo(v)
	return _u
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableTradeNo(v *string) *OrderUpdate {
	if v != nil {
		_u.SetTradeNo(*v)
	}
	return _u
}

// ClearTradeNo clears the value of the "trade_no" field.
func (_u *OrderUpdate) ClearTradeNo() *OrderUpdate {
	_u.mutation.ClearTradeNo()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdate) SetStatus(v string) *OrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableStatus(v *string) *OrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *OrderUpdate) SetCreatedAt(v time.Time) *OrderUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableCreatedAt(v *time.Time) *OrderUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *OrderUpdate) SetPaidAt(v time.Time) *OrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *OrderUpdate) SetNillablePaidAt(v *time.Time) *OrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *OrderUpdate) ClearPaidAt() *OrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *OrderUpdate) SetExpiredAt(v time.Time) *OrderUpdate {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableExpiredAt(v *time.Time) *OrderUpdate {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *OrderUpdate) SetNotes(v string) *OrderUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableNotes(v *string) *OrderUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetCallbackData sets the "callback_data" field.
func (_u *OrderUpdate) SetCallbackData(v string) *OrderUpdate {
	_u.mutation.SetCallbackData(v)
	return _u
}

// SetNillableCallbackData sets the "callback_data" field if the given value is not nil.
func (_u *OrderUpdate) SetNillableCallbackData(v *string) *OrderUpdate {
	if v != nil {
		_u.SetCallbackData(*v)
	}
	return _u
}

// ClearCallbackData clears the value of the "callback_data" field.
func (_u *OrderUpdate) ClearCallbackData() *OrderUpdate {
	_u.mutation.ClearCallbackData()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OrderUpdate) SetUser(v *User) *OrderUpdate {
	return _u.SetUserID(v.ID)
}

// SetProduct sets the "product" edge to the RechargeProduct entity.
func (_u *OrderUpdate) SetProduct(v *RechargeProduct) *OrderUpdate {
	return _u.SetProductID(v.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdate) Mutation() *OrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OrderUpdate) ClearUser() *OrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearProduct clears the "product" edge to the RechargeProduct entity.
func (_u *OrderUpdate) ClearProduct() *OrderUpdate {
	_u.mutation.ClearProduct()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := order.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "Order.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := order.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Order.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := order.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "Order.product_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentMethod(); ok {
		if err := order.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "Order.payment_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentGateway(); ok {
		if err := order.PaymentGatewayValidator(v); err != nil {
			return &ValidationError{Name: "payment_gateway", err: fmt.Errorf(`ent: validator failed for field "Order.payment_gateway": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TradeNo(); ok {
		if err := order.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "Order.trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.user"`)
	}
	return nil
}

func (_u *OrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(order.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(order.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(order.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BonusAmount(); ok {
		_spec.SetField(order.FieldBonusAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBonusAmount(); ok {
		_spec.AddField(order.FieldBonusAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualAmount(); ok {
		_spec.SetField(order.FieldActualAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualAmount(); ok {
		_spec.AddField(order.FieldActualAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(order.FieldPaymentMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentGateway(); ok {
		_spec.SetField(order.FieldPaymentGateway, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradeNo(); ok {
		_spec.SetField(order.FieldTradeNo, field.TypeString, value)
	}
	if _u.mutation.TradeNoCleared() {
		_spec.ClearField(order.FieldTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(order.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(order.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(order.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(order.FieldExpiredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(order.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.CallbackData(); ok {
		_spec.SetField(order.FieldCallbackData, field.TypeString, value)
	}
	if _u.mutation.CallbackDataCleared() {
		_spec.ClearField(order.FieldCallbackData, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ProductTable,
			Columns: []string{order.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeproduct.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ProductTable,
			Columns: []string{order.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderMutation
}

// SetOrderNo sets the "order_no" field.
func (_u *OrderUpdateOne) SetOrderNo(v string) *OrderUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableOrderNo(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrderUpdateOne) SetUserID(v int64) *OrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableUserID(v *int64) *OrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *OrderUpdateOne) SetProductID(v int64) *OrderUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableProductID(v *int64) *OrderUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// ClearProductID clears the value of the "product_id" field.
func (_u *OrderUpdateOne) ClearProductID() *OrderUpdateOne {
	_u.mutation.ClearProductID()
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *OrderUpdateOne) SetProductName(v string) *OrderUpdateOne {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableProductName(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *OrderUpdateOne) SetAmount(v float64) *OrderUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableAmount(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *OrderUpdateOne) AddAmount(v float64) *OrderUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBonusAmount sets the "bonus_amount" field.
func (_u *OrderUpdateOne) SetBonusAmount(v float64) *OrderUpdateOne {
	_u.mutation.ResetBonusAmount()
	_u.mutation.SetBonusAmount(v)
	return _u
}

// SetNillableBonusAmount sets the "bonus_amount" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableBonusAmount(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetBonusAmount(*v)
	}
	return _u
}

// AddBonusAmount adds value to the "bonus_amount" field.
func (_u *OrderUpdateOne) AddBonusAmount(v float64) *OrderUpdateOne {
	_u.mutation.AddBonusAmount(v)
	return _u
}

// SetActualAmount sets the "actual_amount" field.
func (_u *OrderUpdateOne) SetActualAmount(v float64) *OrderUpdateOne {
	_u.mutation.ResetActualAmount()
	_u.mutation.SetActualAmount(v)
	return _u
}

// SetNillableActualAmount sets the "actual_amount" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableActualAmount(v *float64) *OrderUpdateOne {
	if v != nil {
		_u.SetActualAmount(*v)
	}
	return _u
}

// AddActualAmount adds value to the "actual_amount" field.
func (_u *OrderUpdateOne) AddActualAmount(v float64) *OrderUpdateOne {
	_u.mutation.AddActualAmount(v)
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *OrderUpdateOne) SetPaymentMethod(v string) *OrderUpdateOne {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillablePaymentMethod(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// SetPaymentGateway sets the "payment_gateway" field.
func (_u *OrderUpdateOne) SetPaymentGateway(v string) *OrderUpdateOne {
	_u.mutation.SetPaymentGateway(v)
	return _u
}

// SetNillablePaymentGateway sets the "payment_gateway" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillablePaymentGateway(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetPaymentGateway(*v)
	}
	return _u
}

// SetTradeNo sets the "trade_no" field.
func (_u *OrderUpdateOne) SetTradeNo(v string) *OrderUpdateOne {
	_u.mutation.SetTradeNo(v)
	return _u
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableTradeNo(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetTradeNo(*v)
	}
	return _u
}

// ClearTradeNo clears the value of the "trade_no" field.
func (_u *OrderUpdateOne) ClearTradeNo() *OrderUpdateOne {
	_u.mutation.ClearTradeNo()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderUpdateOne) SetStatus(v string) *OrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableStatus(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *OrderUpdateOne) SetCreatedAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableCreatedAt(v *time.Time) *OrderUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *OrderUpdateOne) SetPaidAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillablePaidAt(v *time.Time) *OrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *OrderUpdateOne) ClearPaidAt() *OrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *OrderUpdateOne) SetExpiredAt(v time.Time) *OrderUpdateOne {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableExpiredAt(v *time.Time) *OrderUpdateOne {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *OrderUpdateOne) SetNotes(v string) *OrderUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableNotes(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetCallbackData sets the "callback_data" field.
func (_u *OrderUpdateOne) SetCallbackData(v string) *OrderUpdateOne {
	_u.mutation.SetCallbackData(v)
	return _u
}

// SetNillableCallbackData sets the "callback_data" field if the given value is not nil.
func (_u *OrderUpdateOne) SetNillableCallbackData(v *string) *OrderUpdateOne {
	if v != nil {
		_u.SetCallbackData(*v)
	}
	return _u
}

// ClearCallbackData clears the value of the "callback_data" field.
func (_u *OrderUpdateOne) ClearCallbackData() *OrderUpdateOne {
	_u.mutation.ClearCallbackData()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OrderUpdateOne) SetUser(v *User) *OrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetProduct sets the "product" edge to the RechargeProduct entity.
func (_u *OrderUpdateOne) SetProduct(v *RechargeProduct) *OrderUpdateOne {
	return _u.SetProductID(v.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (_u *OrderUpdateOne) Mutation() *OrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OrderUpdateOne) ClearUser() *OrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearProduct clears the "product" edge to the RechargeProduct entity.
func (_u *OrderUpdateOne) ClearProduct() *OrderUpdateOne {
	_u.mutation.ClearProduct()
	return _u
}

// Where appends a list predicates to the OrderUpdate builder.
func (_u *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Order entity.
func (_u *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := order.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "Order.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := order.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Order.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductName(); ok {
		if err := order.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "Order.product_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentMethod(); ok {
		if err := order.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "Order.payment_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentGateway(); ok {
		if err := order.PaymentGatewayValidator(v); err != nil {
			return &ValidationError{Name: "payment_gateway", err: fmt.Errorf(`ent: validator failed for field "Order.payment_gateway": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TradeNo(); ok {
		if err := order.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "Order.trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Order.user"`)
	}
	return nil
}

func (_u *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(order.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(order.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(order.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BonusAmount(); ok {
		_spec.SetField(order.FieldBonusAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBonusAmount(); ok {
		_spec.AddField(order.FieldBonusAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualAmount(); ok {
		_spec.SetField(order.FieldActualAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualAmount(); ok {
		_spec.AddField(order.FieldActualAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(order.FieldPaymentMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.PaymentGateway(); ok {
		_spec.SetField(order.FieldPaymentGateway, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradeNo(); ok {
		_spec.SetField(order.FieldTradeNo, field.TypeString, value)
	}
	if _u.mutation.TradeNoCleared() {
		_spec.ClearField(order.FieldTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(order.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(order.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(order.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(order.FieldExpiredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(order.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.CallbackData(); ok {
		_spec.SetField(order.FieldCallbackData, field.TypeString, value)
	}
	if _u.mutation.CallbackDataCleared() {
		_spec.ClearField(order.FieldCallbackData, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ProductTable,
			Columns: []string{order.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeproduct.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ProductTable,
			Columns: []string{order.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Order{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
