// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/order"
	"github.com/Wei-Shaw/sub2api/ent/rechargeproduct"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// OrderCreate is the builder for creating a Order entity.
type OrderCreate struct {
	config
	mutation *OrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrderNo sets the "order_no" field.
func (_c *OrderCreate) SetOrderNo(v string) *OrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OrderCreate) SetUserID(v int64) *OrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProductID sets the "product_id" field.
func (_c *OrderCreate) SetProductID(v int64) *OrderCreate {
	_c.mutation.SetProductID(v)
	return _c
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_c *OrderCreate) SetNillableProductID(v *int64) *OrderCreate {
	if v != nil {
		_c.SetProductID(*v)
	}
	return _c
}

// SetProductName sets the "product_name" field.
func (_c *OrderCreate) SetProductName(v string) *OrderCreate {
	_c.mutation.SetProductName(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *OrderCreate) SetAmount(v float64) *OrderCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetBonusAmount sets the "bonus_amount" field.
func (_c *OrderCreate) SetBonusAmount(v float64) *OrderCreate {
	_c.mutation.SetBonusAmount(v)
	return _c
}

// SetNillableBonusAmount sets the "bonus_amount" field if the given value is not nil.
func (_c *OrderCreate) SetNillableBonusAmount(v *float64) *OrderCreate {
	if v != nil {
		_c.SetBonusAmount(*v)
	}
	return _c
}

// SetActualAmount sets the "actual_amount" field.
func (_c *OrderCreate) SetActualAmount(v float64) *OrderCreate {
	_c.mutation.SetActualAmount(v)
	return _c
}

// SetPaymentMethod sets the "payment_method" field.
func (_c *OrderCreate) SetPaymentMethod(v string) *OrderCreate {
	_c.mutation.SetPaymentMethod(v)
	return _c
}

// SetPaymentGateway sets the "payment_gateway" field.
func (_c *OrderCreate) SetPaymentGateway(v string) *OrderCreate {
	_c.mutation.SetPaymentGateway(v)
	return _c
}

// SetNillablePaymentGateway sets the "payment_gateway" field if the given value is not nil.
func (_c *OrderCreate) SetNillablePaymentGateway(v *string) *OrderCreate {
	if v != nil {
		_c.SetPaymentGateway(*v)
	}
	return _c
}

// SetTradeNo sets the "trade_no" field.
func (_c *OrderCreate) SetTradeNo(v string) *OrderCreate {
	_c.mutation.SetTradeNo(v)
	return _c
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_c *OrderCreate) SetNillableTradeNo(v *string) *OrderCreate {
	if v != nil {
		_c.SetTradeNo(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OrderCreate) SetStatus(v string) *OrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OrderCreate) SetNillableStatus(v *string) *OrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrderCreate) SetCreatedAt(v time.Time) *OrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *OrderCreate) SetPaidAt(v time.Time) *OrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *OrderCreate) SetNillablePaidAt(v *time.Time) *OrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetExpiredAt sets the "expired_at" field.
func (_c *OrderCreate) SetExpiredAt(v time.Time) *OrderCreate {
	_c.mutation.SetExpiredAt(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *OrderCreate) SetNotes(v string) *OrderCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *OrderCreate) SetNillableNotes(v *string) *OrderCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCallbackData sets the "callback_data" field.
func (_c *OrderCreate) SetCallbackData(v string) *OrderCreate {
	_c.mutation.SetCallbackData(v)
	return _c
}

// SetNillableCallbackData sets the "callback_data" field if the given value is not nil.
func (_c *OrderCreate) SetNillableCallbackData(v *string) *OrderCreate {
	if v != nil {
		_c.SetCallbackData(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *OrderCreate) SetUser(v *User) *OrderCreate {
	return _c.SetUserID(v.ID)
}

// SetProduct sets the "product" edge to the RechargeProduct entity.
func (_c *OrderCreate) SetProduct(v *RechargeProduct) *OrderCreate {
	return _c.SetProductID(v.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (_c *OrderCreate) Mutation() *OrderMutation {
	return _c.mutation
}

// Save creates the Order in the database.
func (_c *OrderCreate) Save(ctx context.Context) (*Order, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrderCreate) SaveX(ctx context.Context) *Order {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrderCreate) defaults() {
	if _, ok := _c.mutation.BonusAmount(); !ok {
		v := order.DefaultBonusAmount
		_c.mutation.SetBonusAmount(v)
	}
	if _, ok := _c.mutation.PaymentGateway(); !ok {
		v := order.DefaultPaymentGateway
		_c.mutation.SetPaymentGateway(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := order.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := order.DefaultNotes
		_c.mutation.SetNotes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrderCreate) check() error {
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "Order.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := order.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "Order.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Order.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := order.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Order.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProductName(); !ok {
		return &ValidationError{Name: "product_name", err: errors.New(`ent: missing required field "Order.product_name"`)}
	}
	if v, ok := _c.mutation.ProductName(); ok {
		if err := order.ProductNameValidator(v); err != nil {
			return &ValidationError{Name: "product_name", err: fmt.Errorf(`ent: validator failed for field "Order.product_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Order.amount"`)}
	}
	if _, ok := _c.mutation.BonusAmount(); !ok {
		return &ValidationError{Name: "bonus_amount", err: errors.New(`ent: missing required field "Order.bonus_amount"`)}
	}
	if _, ok := _c.mutation.ActualAmount(); !ok {
		return &ValidationError{Name: "actual_amount", err: errors.New(`ent: missing required field "Order.actual_amount"`)}
	}
	if _, ok := _c.mutation.PaymentMethod(); !ok {
		return &ValidationError{Name: "payment_method", err: errors.New(`ent: missing required field "Order.payment_method"`)}
	}
	if v, ok := _c.mutation.PaymentMethod(); ok {
		if err := order.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "Order.payment_method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PaymentGateway(); !ok {
		return &ValidationError{Name: "payment_gateway", err: errors.New(`ent: missing required field "Order.payment_gateway"`)}
	}
	if v, ok := _c.mutation.PaymentGateway(); ok {
		if err := order.PaymentGatewayValidator(v); err != nil {
			return &ValidationError{Name: "payment_gateway", err: fmt.Errorf(`ent: validator failed for field "Order.payment_gateway": %w`, err)}
		}
	}
	if v, ok := _c.mutation.TradeNo(); ok {
		if err := order.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "Order.trade_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Order.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Order.created_at"`)}
	}
	if _, ok := _c.mutation.ExpiredAt(); !ok {
		return &ValidationError{Name: "expired_at", err: errors.New(`ent: missing required field "Order.expired_at"`)}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "Order.notes"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Order.user"`)}
	}
	return nil
}

func (_c *OrderCreate) sqlSave(ctx context.Context) (*Order, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrderCreate) createSpec() (*Order, *sqlgraph.CreateSpec) {
	var (
		_node = &Order{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(order.Table, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(order.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.ProductName(); ok {
		_spec.SetField(order.FieldProductName, field.TypeString, value)
		_node.ProductName = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.BonusAmount(); ok {
		_spec.SetField(order.FieldBonusAmount, field.TypeFloat64, value)
		_node.BonusAmount = value
	}
	if value, ok := _c.mutation.ActualAmount(); ok {
		_spec.SetField(order.FieldActualAmount, field.TypeFloat64, value)
		_node.ActualAmount = value
	}
	if value, ok := _c.mutation.PaymentMethod(); ok {
		_spec.SetField(order.FieldPaymentMethod, field.TypeString, value)
		_node.PaymentMethod = value
	}
	if value, ok := _c.mutation.PaymentGateway(); ok {
		_spec.SetField(order.FieldPaymentGateway, field.TypeString, value)
		_node.PaymentGateway = value
	}
	if value, ok := _c.mutation.TradeNo(); ok {
		_spec.SetField(order.FieldTradeNo, field.TypeString, value)
		_node.TradeNo = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(order.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(order.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.ExpiredAt(); ok {
		_spec.SetField(order.FieldExpiredAt, field.TypeTime, value)
		_node.ExpiredAt = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(order.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.CallbackData(); ok {
		_spec.SetField(order.FieldCallbackData, field.TypeString, value)
		_node.CallbackData = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.ProductTable,
			Columns: []string{order.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rechargeproduct.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Order.Create().
//		SetOrderNo(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrderUpsert) {
//			SetOrderNo(v+v).
//		}).
//		Exec(ctx)
func (_c *OrderCreate) OnConflict(opts ...sql.ConflictOption) *OrderUpsertOne {
	_c.conflict = opts
	return &OrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrderCreate) OnConflictColumns(columns ...string) *OrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrderUpsertOne{
		create: _c,
	}
}

type (
	// OrderUpsertOne is the builder for "upsert"-ing
	//  one Order node.
	OrderUpsertOne struct {
		create *OrderCreate
	}

	// OrderUpsert is the "OnConflict" setter.
	OrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrderNo sets the "order_no" field.
func (u *OrderUpsert) SetOrderNo(v string) *OrderUpsert {
	u.Set(order.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *OrderUpsert) UpdateOrderNo() *OrderUpsert {
	u.SetExcluded(order.FieldOrderNo)
	return u
}

// SetUserID sets the "user_id" field.
func (u *OrderUpsert) SetUserID(v int64) *OrderUpsert {
	u.Set(order.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrderUpsert) UpdateUserID() *OrderUpsert {
	u.SetExcluded(order.FieldUserID)
	return u
}

// SetProductID sets the "product_id" field.
func (u *OrderUpsert) SetProductID(v int64) *OrderUpsert {
	u.Set(order.FieldProductID, v)
	return u
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *OrderUpsert) UpdateProductID() *OrderUpsert {
	u.SetExcluded(order.FieldProductID)
	return u
}

// ClearProductID clears the value of the "product_id" field.
func (u *OrderUpsert) ClearProductID() *OrderUpsert {
	u.SetNull(order.FieldProductID)
	return u
}

// SetProductName sets the "product_name" field.
func (u *OrderUpsert) SetProductName(v string) *OrderUpsert {
	u.Set(order.FieldProductName, v)
	return u
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *OrderUpsert) UpdateProductName() *OrderUpsert {
	u.SetExcluded(order.FieldProductName)
	return u
}

// SetAmount sets the "amount" field.
func (u *OrderUpsert) SetAmount(v float64) *OrderUpsert {
	u.Set(order.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *OrderUpsert) UpdateAmount() *OrderUpsert {
	u.SetExcluded(order.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *OrderUpsert) AddAmount(v float64) *OrderUpsert {
	u.Add(order.FieldAmount, v)
	return u
}

// SetBonusAmount sets the "bonus_amount" field.
func (u *OrderUpsert) SetBonusAmount(v float64) *OrderUpsert {
	u.Set(order.FieldBonusAmount, v)
	return u
}

// UpdateBonusAmount sets the "bonus_amount" field to the value that was provided on create.
func (u *OrderUpsert) UpdateBonusAmount() *OrderUpsert {
	u.SetExcluded(order.FieldBonusAmount)
	return u
}

// AddBonusAmount adds v to the "bonus_amount" field.
func (u *OrderUpsert) AddBonusAmount(v float64) *OrderUpsert {
	u.Add(order.FieldBonusAmount, v)
	return u
}

// SetActualAmount sets the "actual_amount" field.
func (u *OrderUpsert) SetActualAmount(v float64) *OrderUpsert {
	u.Set(order.FieldActualAmount, v)
	return u
}

// UpdateActualAmount sets the "actual_amount" field to the value that was provided on create.
func (u *OrderUpsert) UpdateActualAmount() *OrderUpsert {
	u.SetExcluded(order.FieldActualAmount)
	return u
}

// AddActualAmount adds v to the "actual_amount" field.
func (u *OrderUpsert) AddActualAmount(v float64) *OrderUpsert {
	u.Add(order.FieldActualAmount, v)
	return u
}

// SetPaymentMethod sets the "payment_method" field.
func (u *OrderUpsert) SetPaymentMethod(v string) *OrderUpsert {
	u.Set(order.FieldPaymentMethod, v)
	return u
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *OrderUpsert) UpdatePaymentMethod() *OrderUpsert {
	u.SetExcluded(order.FieldPaymentMethod)
	return u
}

// SetPaymentGateway sets the "payment_gateway" field.
func (u *OrderUpsert) SetPaymentGateway(v string) *OrderUpsert {
	u.Set(order.FieldPaymentGateway, v)
	return u
}

// UpdatePaymentGateway sets the "payment_gateway" field to the value that was provided on create.
func (u *OrderUpsert) UpdatePaymentGateway() *OrderUpsert {
	u.SetExcluded(order.FieldPaymentGateway)
	return u
}

// SetTradeNo sets the "trade_no" field.
func (u *OrderUpsert) SetTradeNo(v string) *OrderUpsert {
	u.Set(order.FieldTradeNo, v)
	return u
}

// UpdateTradeNo sets the "trade_no" field to the value that was provided on create.
func (u *OrderUpsert) UpdateTradeNo() *OrderUpsert {
	u.SetExcluded(order.FieldTradeNo)
	return u
}

// ClearTradeNo clears the value of the "trade_no" field.
func (u *OrderUpsert) ClearTradeNo() *OrderUpsert {
	u.SetNull(order.FieldTradeNo)
	return u
}

// SetStatus sets the "status" field.
func (u *OrderUpsert) SetStatus(v string) *OrderUpsert {
	u.Set(order.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrderUpsert) UpdateStatus() *OrderUpsert {
	u.SetExcluded(order.FieldStatus)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *OrderUpsert) SetCreatedAt(v time.Time) *OrderUpsert {
	u.Set(order.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *OrderUpsert) UpdateCreatedAt() *OrderUpsert {
	u.SetExcluded(order.FieldCreatedAt)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *OrderUpsert) SetPaidAt(v time.Time) *OrderUpsert {
	u.Set(order.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *OrderUpsert) UpdatePaidAt() *OrderUpsert {
	u.SetExcluded(order.FieldPaidAt)
	return u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *OrderUpsert) ClearPaidAt() *OrderUpsert {
	u.SetNull(order.FieldPaidAt)
	return u
}

// SetExpiredAt sets the "expired_at" field.
func (u *OrderUpsert) SetExpiredAt(v time.Time) *OrderUpsert {
	u.Set(order.FieldExpiredAt, v)
	return u
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *OrderUpsert) UpdateExpiredAt() *OrderUpsert {
	u.SetExcluded(order.FieldExpiredAt)
	return u
}

// SetNotes sets the "notes" field.
func (u *OrderUpsert) SetNotes(v string) *OrderUpsert {
	u.Set(order.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *OrderUpsert) UpdateNotes() *OrderUpsert {
	u.SetExcluded(order.FieldNotes)
	return u
}

// SetCallbackData sets the "callback_data" field.
func (u *OrderUpsert) SetCallbackData(v string) *OrderUpsert {
	u.Set(order.FieldCallbackData, v)
	return u
}

// UpdateCallbackData sets the "callback_data" field to the value that was provided on create.
func (u *OrderUpsert) UpdateCallbackData() *OrderUpsert {
	u.SetExcluded(order.FieldCallbackData)
	return u
}

// ClearCallbackData clears the value of the "callback_data" field.
func (u *OrderUpsert) ClearCallbackData() *OrderUpsert {
	u.SetNull(order.FieldCallbackData)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrderUpsertOne) UpdateNewValues() *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Order.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrderUpsertOne) Ignore() *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrderUpsertOne) DoNothing() *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrderCreate.OnConflict
// documentation for more info.
func (u *OrderUpsertOne) Update(set func(*OrderUpsert)) *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *OrderUpsertOne) SetOrderNo(v string) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateOrderNo() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *OrderUpsertOne) SetUserID(v int64) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateUserID() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUserID()
	})
}

// SetProductID sets the "product_id" field.
func (u *OrderUpsertOne) SetProductID(v int64) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateProductID() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateProductID()
	})
}

// ClearProductID clears the value of the "product_id" field.
func (u *OrderUpsertOne) ClearProductID() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.ClearProductID()
	})
}

// SetProductName sets the "product_name" field.
func (u *OrderUpsertOne) SetProductName(v string) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetProductName(v)
	})
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateProductName() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateProductName()
	})
}

// SetAmount sets the "amount" field.
func (u *OrderUpsertOne) SetAmount(v float64) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *OrderUpsertOne) AddAmount(v float64) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateAmount() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateAmount()
	})
}

// SetBonusAmount sets the "bonus_amount" field.
func (u *OrderUpsertOne) SetBonusAmount(v float64) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetBonusAmount(v)
	})
}

// AddBonusAmount adds v to the "bonus_amount" field.
func (u *OrderUpsertOne) AddBonusAmount(v float64) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.AddBonusAmount(v)
	})
}

// UpdateBonusAmount sets the "bonus_amount" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateBonusAmount() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateBonusAmount()
	})
}

// SetActualAmount sets the "actual_amount" field.
func (u *OrderUpsertOne) SetActualAmount(v float64) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetActualAmount(v)
	})
}

// AddActualAmount adds v to the "actual_amount" field.
func (u *OrderUpsertOne) AddActualAmount(v float64) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.AddActualAmount(v)
	})
}

// UpdateActualAmount sets the "actual_amount" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateActualAmount() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateActualAmount()
	})
}

// SetPaymentMethod sets the "payment_method" field.
func (u *OrderUpsertOne) SetPaymentMethod(v string) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetPaymentMethod(v)
	})
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdatePaymentMethod() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdatePaymentMethod()
	})
}

// SetPaymentGateway sets the "payment_gateway" field.
func (u *OrderUpsertOne) SetPaymentGateway(v string) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetPaymentGateway(v)
	})
}

// UpdatePaymentGateway sets the "payment_gateway" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdatePaymentGateway() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdatePaymentGateway()
	})
}

// SetTradeNo sets the "trade_no" field.
func (u *OrderUpsertOne) SetTradeNo(v string) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetTradeNo(v)
	})
}

// UpdateTradeNo sets the "trade_no" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateTradeNo() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateTradeNo()
	})
}

// ClearTradeNo clears the value of the "trade_no" field.
func (u *OrderUpsertOne) ClearTradeNo() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.ClearTradeNo()
	})
}

// SetStatus sets the "status" field.
func (u *OrderUpsertOne) SetStatus(v string) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateStatus() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *OrderUpsertOne) SetCreatedAt(v time.Time) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateCreatedAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *OrderUpsertOne) SetPaidAt(v time.Time) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdatePaidAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *OrderUpsertOne) ClearPaidAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetExpiredAt sets the "expired_at" field.
func (u *OrderUpsertOne) SetExpiredAt(v time.Time) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetExpiredAt(v)
	})
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateExpiredAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateExpiredAt()
	})
}

// SetNotes sets the "notes" field.
func (u *OrderUpsertOne) SetNotes(v string) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateNotes() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateNotes()
	})
}

// SetCallbackData sets the "callback_data" field.
func (u *OrderUpsertOne) SetCallbackData(v string) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetCallbackData(v)
	})
}

// UpdateCallbackData sets the "callback_data" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateCallbackData() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateCallbackData()
	})
}

// ClearCallbackData clears the value of the "callback_data" field.
func (u *OrderUpsertOne) ClearCallbackData() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.ClearCallbackData()
	})
}

// Exec executes the query.
func (u *OrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OrderCreateBulk is the builder for creating many Order entities in bulk.
type OrderCreateBulk struct {
	config
	err      error
	builders []*OrderCreate
	conflict []sql.ConflictOption
}

// Save creates the Order entities in the database.
func (_c *OrderCreateBulk) Save(ctx context.Context) ([]*Order, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Order, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrderCreateBulk) SaveX(ctx context.Context) []*Order {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Order.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrderUpsert) {
//			SetOrderNo(v+v).
//		}).
//		Exec(ctx)
func (_c *OrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrderUpsertBulk {
	_c.conflict = opts
	return &OrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OrderCreateBulk) OnConflictColumns(columns ...string) *OrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OrderUpsertBulk{
		create: _c,
	}
}

// OrderUpsertBulk is the builder for "upsert"-ing
// a bulk of Order nodes.
type OrderUpsertBulk struct {
	create *OrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrderUpsertBulk) UpdateNewValues() *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrderUpsertBulk) Ignore() *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrderUpsertBulk) DoNothing() *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrderCreateBulk.OnConflict
// documentation for more info.
func (u *OrderUpsertBulk) Update(set func(*OrderUpsert)) *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *OrderUpsertBulk) SetOrderNo(v string) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateOrderNo() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *OrderUpsertBulk) SetUserID(v int64) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateUserID() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUserID()
	})
}

// SetProductID sets the "product_id" field.
func (u *OrderUpsertBulk) SetProductID(v int64) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateProductID() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateProductID()
	})
}

// ClearProductID clears the value of the "product_id" field.
func (u *OrderUpsertBulk) ClearProductID() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.ClearProductID()
	})
}

// SetProductName sets the "product_name" field.
func (u *OrderUpsertBulk) SetProductName(v string) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetProductName(v)
	})
}

// UpdateProductName sets the "product_name" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateProductName() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateProductName()
	})
}

// SetAmount sets the "amount" field.
func (u *OrderUpsertBulk) SetAmount(v float64) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *OrderUpsertBulk) AddAmount(v float64) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateAmount() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateAmount()
	})
}

// SetBonusAmount sets the "bonus_amount" field.
func (u *OrderUpsertBulk) SetBonusAmount(v float64) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetBonusAmount(v)
	})
}

// AddBonusAmount adds v to the "bonus_amount" field.
func (u *OrderUpsertBulk) AddBonusAmount(v float64) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.AddBonusAmount(v)
	})
}

// UpdateBonusAmount sets the "bonus_amount" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateBonusAmount() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateBonusAmount()
	})
}

// SetActualAmount sets the "actual_amount" field.
func (u *OrderUpsertBulk) SetActualAmount(v float64) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetActualAmount(v)
	})
}

// AddActualAmount adds v to the "actual_amount" field.
func (u *OrderUpsertBulk) AddActualAmount(v float64) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.AddActualAmount(v)
	})
}

// UpdateActualAmount sets the "actual_amount" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateActualAmount() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateActualAmount()
	})
}

// SetPaymentMethod sets the "payment_method" field.
func (u *OrderUpsertBulk) SetPaymentMethod(v string) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetPaymentMethod(v)
	})
}

// UpdatePaymentMethod sets the "payment_method" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdatePaymentMethod() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdatePaymentMethod()
	})
}

// SetPaymentGateway sets the "payment_gateway" field.
func (u *OrderUpsertBulk) SetPaymentGateway(v string) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetPaymentGateway(v)
	})
}

// UpdatePaymentGateway sets the "payment_gateway" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdatePaymentGateway() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdatePaymentGateway()
	})
}

// SetTradeNo sets the "trade_no" field.
func (u *OrderUpsertBulk) SetTradeNo(v string) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetTradeNo(v)
	})
}

// UpdateTradeNo sets the "trade_no" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateTradeNo() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateTradeNo()
	})
}

// ClearTradeNo clears the value of the "trade_no" field.
func (u *OrderUpsertBulk) ClearTradeNo() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.ClearTradeNo()
	})
}

// SetStatus sets the "status" field.
func (u *OrderUpsertBulk) SetStatus(v string) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateStatus() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *OrderUpsertBulk) SetCreatedAt(v time.Time) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateCreatedAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *OrderUpsertBulk) SetPaidAt(v time.Time) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdatePaidAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *OrderUpsertBulk) ClearPaidAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetExpiredAt sets the "expired_at" field.
func (u *OrderUpsertBulk) SetExpiredAt(v time.Time) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetExpiredAt(v)
	})
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateExpiredAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateExpiredAt()
	})
}

// SetNotes sets the "notes" field.
func (u *OrderUpsertBulk) SetNotes(v string) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateNotes() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateNotes()
	})
}

// SetCallbackData sets the "callback_data" field.
func (u *OrderUpsertBulk) SetCallbackData(v string) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetCallbackData(v)
	})
}

// UpdateCallbackData sets the "callback_data" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateCallbackData() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateCallbackData()
	})
}

// ClearCallbackData clears the value of the "callback_data" field.
func (u *OrderUpsertBulk) ClearCallbackData() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.ClearCallbackData()
	})
}

// Exec executes the query.
func (u *OrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
