// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/order"
	"github.com/Wei-Shaw/sub2api/ent/rechargeproduct"
)

// RechargeProductCreate is the builder for creating a RechargeProduct entity.
type RechargeProductCreate struct {
	config
	mutation *RechargeProductMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *RechargeProductCreate) SetName(v string) *RechargeProductCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *RechargeProductCreate) SetAmount(v float64) *RechargeProductCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetBalance sets the "balance" field.
func (_c *RechargeProductCreate) SetBalance(v float64) *RechargeProductCreate {
	_c.mutation.SetBalance(v)
	return _c
}

// SetBonusBalance sets the "bonus_balance" field.
func (_c *RechargeProductCreate) SetBonusBalance(v float64) *RechargeProductCreate {
	_c.mutation.SetBonusBalance(v)
	return _c
}

// SetNillableBonusBalance sets the "bonus_balance" field if the given value is not nil.
func (_c *RechargeProductCreate) SetNillableBonusBalance(v *float64) *RechargeProductCreate {
	if v != nil {
		_c.SetBonusBalance(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *RechargeProductCreate) SetDescription(v string) *RechargeProductCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *RechargeProductCreate) SetNillableDescription(v *string) *RechargeProductCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *RechargeProductCreate) SetSortOrder(v int) *RechargeProductCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *RechargeProductCreate) SetNillableSortOrder(v *int) *RechargeProductCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetIsHot sets the "is_hot" field.
func (_c *RechargeProductCreate) SetIsHot(v bool) *RechargeProductCreate {
	_c.mutation.SetIsHot(v)
	return _c
}

// SetNillableIsHot sets the "is_hot" field if the given value is not nil.
func (_c *RechargeProductCreate) SetNillableIsHot(v *bool) *RechargeProductCreate {
	if v != nil {
		_c.SetIsHot(*v)
	}
	return _c
}

// SetDiscountLabel sets the "discount_label" field.
func (_c *RechargeProductCreate) SetDiscountLabel(v string) *RechargeProductCreate {
	_c.mutation.SetDiscountLabel(v)
	return _c
}

// SetNillableDiscountLabel sets the "discount_label" field if the given value is not nil.
func (_c *RechargeProductCreate) SetNillableDiscountLabel(v *string) *RechargeProductCreate {
	if v != nil {
		_c.SetDiscountLabel(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RechargeProductCreate) SetStatus(v string) *RechargeProductCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RechargeProductCreate) SetNillableStatus(v *string) *RechargeProductCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RechargeProductCreate) SetCreatedAt(v time.Time) *RechargeProductCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RechargeProductCreate) SetUpdatedAt(v time.Time) *RechargeProductCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// AddOrderIDs adds the "orders" edge to the Order entity by IDs.
func (_c *RechargeProductCreate) AddOrderIDs(ids ...int64) *RechargeProductCreate {
	_c.mutation.AddOrderIDs(ids...)
	return _c
}

// AddOrders adds the "orders" edges to the Order entity.
func (_c *RechargeProductCreate) AddOrders(v ...*Order) *RechargeProductCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOrderIDs(ids...)
}

// Mutation returns the RechargeProductMutation object of the builder.
func (_c *RechargeProductCreate) Mutation() *RechargeProductMutation {
	return _c.mutation
}

// Save creates the RechargeProduct in the database.
func (_c *RechargeProductCreate) Save(ctx context.Context) (*RechargeProduct, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RechargeProductCreate) SaveX(ctx context.Context) *RechargeProduct {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RechargeProductCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RechargeProductCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RechargeProductCreate) defaults() {
	if _, ok := _c.mutation.BonusBalance(); !ok {
		v := rechargeproduct.DefaultBonusBalance
		_c.mutation.SetBonusBalance(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := rechargeproduct.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := rechargeproduct.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.IsHot(); !ok {
		v := rechargeproduct.DefaultIsHot
		_c.mutation.SetIsHot(v)
	}
	if _, ok := _c.mutation.DiscountLabel(); !ok {
		v := rechargeproduct.DefaultDiscountLabel
		_c.mutation.SetDiscountLabel(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := rechargeproduct.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RechargeProductCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RechargeProduct.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := rechargeproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RechargeProduct.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "RechargeProduct.amount"`)}
	}
	if _, ok := _c.mutation.Balance(); !ok {
		return &ValidationError{Name: "balance", err: errors.New(`ent: missing required field "RechargeProduct.balance"`)}
	}
	if _, ok := _c.mutation.BonusBalance(); !ok {
		return &ValidationError{Name: "bonus_balance", err: errors.New(`ent: missing required field "RechargeProduct.bonus_balance"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "RechargeProduct.description"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "RechargeProduct.sort_order"`)}
	}
	if _, ok := _c.mutation.IsHot(); !ok {
		return &ValidationError{Name: "is_hot", err: errors.New(`ent: missing required field "RechargeProduct.is_hot"`)}
	}
	if _, ok := _c.mutation.DiscountLabel(); !ok {
		return &ValidationError{Name: "discount_label", err: errors.New(`ent: missing required field "RechargeProduct.discount_label"`)}
	}
	if v, ok := _c.mutation.DiscountLabel(); ok {
		if err := rechargeproduct.DiscountLabelValidator(v); err != nil {
			return &ValidationError{Name: "discount_label", err: fmt.Errorf(`ent: validator failed for field "RechargeProduct.discount_label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RechargeProduct.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := rechargeproduct.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RechargeProduct.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RechargeProduct.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RechargeProduct.updated_at"`)}
	}
	return nil
}

func (_c *RechargeProductCreate) sqlSave(ctx context.Context) (*RechargeProduct, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RechargeProductCreate) createSpec() (*RechargeProduct, *sqlgraph.CreateSpec) {
	var (
		_node = &RechargeProduct{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rechargeproduct.Table, sqlgraph.NewFieldSpec(rechargeproduct.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(rechargeproduct.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(rechargeproduct.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Balance(); ok {
		_spec.SetField(rechargeproduct.FieldBalance, field.TypeFloat64, value)
		_node.Balance = value
	}
	if value, ok := _c.mutation.BonusBalance(); ok {
		_spec.SetField(rechargeproduct.FieldBonusBalance, field.TypeFloat64, value)
		_node.BonusBalance = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(rechargeproduct.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(rechargeproduct.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.IsHot(); ok {
		_spec.SetField(rechargeproduct.FieldIsHot, field.TypeBool, value)
		_node.IsHot = value
	}
	if value, ok := _c.mutation.DiscountLabel(); ok {
		_spec.SetField(rechargeproduct.FieldDiscountLabel, field.TypeString, value)
		_node.DiscountLabel = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(rechargeproduct.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rechargeproduct.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargeproduct.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeproduct.OrdersTable,
			Columns: []string{rechargeproduct.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RechargeProduct.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RechargeProductUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *RechargeProductCreate) OnConflict(opts ...sql.ConflictOption) *RechargeProductUpsertOne {
	_c.conflict = opts
	return &RechargeProductUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RechargeProduct.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RechargeProductCreate) OnConflictColumns(columns ...string) *RechargeProductUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RechargeProductUpsertOne{
		create: _c,
	}
}

type (
	// RechargeProductUpsertOne is the builder for "upsert"-ing
	//  one RechargeProduct node.
	RechargeProductUpsertOne struct {
		create *RechargeProductCreate
	}

	// RechargeProductUpsert is the "OnConflict" setter.
	RechargeProductUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *RechargeProductUpsert) SetName(v string) *RechargeProductUpsert {
	u.Set(rechargeproduct.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RechargeProductUpsert) UpdateName() *RechargeProductUpsert {
	u.SetExcluded(rechargeproduct.FieldName)
	return u
}

// SetAmount sets the "amount" field.
func (u *RechargeProductUpsert) SetAmount(v float64) *RechargeProductUpsert {
	u.Set(rechargeproduct.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RechargeProductUpsert) UpdateAmount() *RechargeProductUpsert {
	u.SetExcluded(rechargeproduct.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *RechargeProductUpsert) AddAmount(v float64) *RechargeProductUpsert {
	u.Add(rechargeproduct.FieldAmount, v)
	return u
}

// SetBalance sets the "balance" field.
func (u *RechargeProductUpsert) SetBalance(v float64) *RechargeProductUpsert {
	u.Set(rechargeproduct.FieldBalance, v)
	return u
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *RechargeProductUpsert) UpdateBalance() *RechargeProductUpsert {
	u.SetExcluded(rechargeproduct.FieldBalance)
	return u
}

// AddBalance adds v to the "balance" field.
func (u *RechargeProductUpsert) AddBalance(v float64) *RechargeProductUpsert {
	u.Add(rechargeproduct.FieldBalance, v)
	return u
}

// SetBonusBalance sets the "bonus_balance" field.
func (u *RechargeProductUpsert) SetBonusBalance(v float64) *RechargeProductUpsert {
	u.Set(rechargeproduct.FieldBonusBalance, v)
	return u
}

// UpdateBonusBalance sets the "bonus_balance" field to the value that was provided on create.
func (u *RechargeProductUpsert) UpdateBonusBalance() *RechargeProductUpsert {
	u.SetExcluded(rechargeproduct.FieldBonusBalance)
	return u
}

// AddBonusBalance adds v to the "bonus_balance" field.
func (u *RechargeProductUpsert) AddBonusBalance(v float64) *RechargeProductUpsert {
	u.Add(rechargeproduct.FieldBonusBalance, v)
	return u
}

// SetDescription sets the "description" field.
func (u *RechargeProductUpsert) SetDescription(v string) *RechargeProductUpsert {
	u.Set(rechargeproduct.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RechargeProductUpsert) UpdateDescription() *RechargeProductUpsert {
	u.SetExcluded(rechargeproduct.FieldDescription)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *RechargeProductUpsert) SetSortOrder(v int) *RechargeProductUpsert {
	u.Set(rechargeproduct.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *RechargeProductUpsert) UpdateSortOrder() *RechargeProductUpsert {
	u.SetExcluded(rechargeproduct.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *RechargeProductUpsert) AddSortOrder(v int) *RechargeProductUpsert {
	u.Add(rechargeproduct.FieldSortOrder, v)
	return u
}

// SetIsHot sets the "is_hot" field.
func (u *RechargeProductUpsert) SetIsHot(v bool) *RechargeProductUpsert {
	u.Set(rechargeproduct.FieldIsHot, v)
	return u
}

// UpdateIsHot sets the "is_hot" field to the value that was provided on create.
func (u *RechargeProductUpsert) UpdateIsHot() *RechargeProductUpsert {
	u.SetExcluded(rechargeproduct.FieldIsHot)
	return u
}

// SetDiscountLabel sets the "discount_label" field.
func (u *RechargeProductUpsert) SetDiscountLabel(v string) *RechargeProductUpsert {
	u.Set(rechargeproduct.FieldDiscountLabel, v)
	return u
}

// UpdateDiscountLabel sets the "discount_label" field to the value that was provided on create.
func (u *RechargeProductUpsert) UpdateDiscountLabel() *RechargeProductUpsert {
	u.SetExcluded(rechargeproduct.FieldDiscountLabel)
	return u
}

// SetStatus sets the "status" field.
func (u *RechargeProductUpsert) SetStatus(v string) *RechargeProductUpsert {
	u.Set(rechargeproduct.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RechargeProductUpsert) UpdateStatus() *RechargeProductUpsert {
	u.SetExcluded(rechargeproduct.FieldStatus)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *RechargeProductUpsert) SetCreatedAt(v time.Time) *RechargeProductUpsert {
	u.Set(rechargeproduct.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RechargeProductUpsert) UpdateCreatedAt() *RechargeProductUpsert {
	u.SetExcluded(rechargeproduct.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeProductUpsert) SetUpdatedAt(v time.Time) *RechargeProductUpsert {
	u.Set(rechargeproduct.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeProductUpsert) UpdateUpdatedAt() *RechargeProductUpsert {
	u.SetExcluded(rechargeproduct.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RechargeProduct.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RechargeProductUpsertOne) UpdateNewValues() *RechargeProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RechargeProduct.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RechargeProductUpsertOne) Ignore() *RechargeProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RechargeProductUpsertOne) DoNothing() *RechargeProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RechargeProductCreate.OnConflict
// documentation for more info.
func (u *RechargeProductUpsertOne) Update(set func(*RechargeProductUpsert)) *RechargeProductUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RechargeProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *RechargeProductUpsertOne) SetName(v string) *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RechargeProductUpsertOne) UpdateName() *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateName()
	})
}

// SetAmount sets the "amount" field.
func (u *RechargeProductUpsertOne) SetAmount(v float64) *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *RechargeProductUpsertOne) AddAmount(v float64) *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RechargeProductUpsertOne) UpdateAmount() *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateAmount()
	})
}

// SetBalance sets the "balance" field.
func (u *RechargeProductUpsertOne) SetBalance(v float64) *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *RechargeProductUpsertOne) AddBalance(v float64) *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *RechargeProductUpsertOne) UpdateBalance() *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateBalance()
	})
}

// SetBonusBalance sets the "bonus_balance" field.
func (u *RechargeProductUpsertOne) SetBonusBalance(v float64) *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetBonusBalance(v)
	})
}

// AddBonusBalance adds v to the "bonus_balance" field.
func (u *RechargeProductUpsertOne) AddBonusBalance(v float64) *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.AddBonusBalance(v)
	})
}

// UpdateBonusBalance sets the "bonus_balance" field to the value that was provided on create.
func (u *RechargeProductUpsertOne) UpdateBonusBalance() *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateBonusBalance()
	})
}

// SetDescription sets the "description" field.
func (u *RechargeProductUpsertOne) SetDescription(v string) *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RechargeProductUpsertOne) UpdateDescription() *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateDescription()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *RechargeProductUpsertOne) SetSortOrder(v int) *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *RechargeProductUpsertOne) AddSortOrder(v int) *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *RechargeProductUpsertOne) UpdateSortOrder() *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateSortOrder()
	})
}

// SetIsHot sets the "is_hot" field.
func (u *RechargeProductUpsertOne) SetIsHot(v bool) *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetIsHot(v)
	})
}

// UpdateIsHot sets the "is_hot" field to the value that was provided on create.
func (u *RechargeProductUpsertOne) UpdateIsHot() *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateIsHot()
	})
}

// SetDiscountLabel sets the "discount_label" field.
func (u *RechargeProductUpsertOne) SetDiscountLabel(v string) *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetDiscountLabel(v)
	})
}

// UpdateDiscountLabel sets the "discount_label" field to the value that was provided on create.
func (u *RechargeProductUpsertOne) UpdateDiscountLabel() *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateDiscountLabel()
	})
}

// SetStatus sets the "status" field.
func (u *RechargeProductUpsertOne) SetStatus(v string) *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RechargeProductUpsertOne) UpdateStatus() *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *RechargeProductUpsertOne) SetCreatedAt(v time.Time) *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RechargeProductUpsertOne) UpdateCreatedAt() *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeProductUpsertOne) SetUpdatedAt(v time.Time) *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeProductUpsertOne) UpdateUpdatedAt() *RechargeProductUpsertOne {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RechargeProductUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RechargeProductCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RechargeProductUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RechargeProductUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RechargeProductUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RechargeProductCreateBulk is the builder for creating many RechargeProduct entities in bulk.
type RechargeProductCreateBulk struct {
	config
	err      error
	builders []*RechargeProductCreate
	conflict []sql.ConflictOption
}

// Save creates the RechargeProduct entities in the database.
func (_c *RechargeProductCreateBulk) Save(ctx context.Context) ([]*RechargeProduct, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RechargeProduct, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RechargeProductMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RechargeProductCreateBulk) SaveX(ctx context.Context) []*RechargeProduct {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RechargeProductCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RechargeProductCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RechargeProduct.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RechargeProductUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *RechargeProductCreateBulk) OnConflict(opts ...sql.ConflictOption) *RechargeProductUpsertBulk {
	_c.conflict = opts
	return &RechargeProductUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RechargeProduct.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RechargeProductCreateBulk) OnConflictColumns(columns ...string) *RechargeProductUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RechargeProductUpsertBulk{
		create: _c,
	}
}

// RechargeProductUpsertBulk is the builder for "upsert"-ing
// a bulk of RechargeProduct nodes.
type RechargeProductUpsertBulk struct {
	create *RechargeProductCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RechargeProduct.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RechargeProductUpsertBulk) UpdateNewValues() *RechargeProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RechargeProduct.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RechargeProductUpsertBulk) Ignore() *RechargeProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RechargeProductUpsertBulk) DoNothing() *RechargeProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RechargeProductCreateBulk.OnConflict
// documentation for more info.
func (u *RechargeProductUpsertBulk) Update(set func(*RechargeProductUpsert)) *RechargeProductUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RechargeProductUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *RechargeProductUpsertBulk) SetName(v string) *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *RechargeProductUpsertBulk) UpdateName() *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateName()
	})
}

// SetAmount sets the "amount" field.
func (u *RechargeProductUpsertBulk) SetAmount(v float64) *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *RechargeProductUpsertBulk) AddAmount(v float64) *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *RechargeProductUpsertBulk) UpdateAmount() *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateAmount()
	})
}

// SetBalance sets the "balance" field.
func (u *RechargeProductUpsertBulk) SetBalance(v float64) *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetBalance(v)
	})
}

// AddBalance adds v to the "balance" field.
func (u *RechargeProductUpsertBulk) AddBalance(v float64) *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.AddBalance(v)
	})
}

// UpdateBalance sets the "balance" field to the value that was provided on create.
func (u *RechargeProductUpsertBulk) UpdateBalance() *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateBalance()
	})
}

// SetBonusBalance sets the "bonus_balance" field.
func (u *RechargeProductUpsertBulk) SetBonusBalance(v float64) *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetBonusBalance(v)
	})
}

// AddBonusBalance adds v to the "bonus_balance" field.
func (u *RechargeProductUpsertBulk) AddBonusBalance(v float64) *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.AddBonusBalance(v)
	})
}

// UpdateBonusBalance sets the "bonus_balance" field to the value that was provided on create.
func (u *RechargeProductUpsertBulk) UpdateBonusBalance() *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateBonusBalance()
	})
}

// SetDescription sets the "description" field.
func (u *RechargeProductUpsertBulk) SetDescription(v string) *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *RechargeProductUpsertBulk) UpdateDescription() *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateDescription()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *RechargeProductUpsertBulk) SetSortOrder(v int) *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *RechargeProductUpsertBulk) AddSortOrder(v int) *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *RechargeProductUpsertBulk) UpdateSortOrder() *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateSortOrder()
	})
}

// SetIsHot sets the "is_hot" field.
func (u *RechargeProductUpsertBulk) SetIsHot(v bool) *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetIsHot(v)
	})
}

// UpdateIsHot sets the "is_hot" field to the value that was provided on create.
func (u *RechargeProductUpsertBulk) UpdateIsHot() *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateIsHot()
	})
}

// SetDiscountLabel sets the "discount_label" field.
func (u *RechargeProductUpsertBulk) SetDiscountLabel(v string) *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetDiscountLabel(v)
	})
}

// UpdateDiscountLabel sets the "discount_label" field to the value that was provided on create.
func (u *RechargeProductUpsertBulk) UpdateDiscountLabel() *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateDiscountLabel()
	})
}

// SetStatus sets the "status" field.
func (u *RechargeProductUpsertBulk) SetStatus(v string) *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RechargeProductUpsertBulk) UpdateStatus() *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateStatus()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *RechargeProductUpsertBulk) SetCreatedAt(v time.Time) *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *RechargeProductUpsertBulk) UpdateCreatedAt() *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargeProductUpsertBulk) SetUpdatedAt(v time.Time) *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargeProductUpsertBulk) UpdateUpdatedAt() *RechargeProductUpsertBulk {
	return u.Update(func(s *RechargeProductUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RechargeProductUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RechargeProductCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RechargeProductCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RechargeProductUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
