// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/order"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rechargeproduct"
)

// RechargeProductUpdate is the builder for updating RechargeProduct entities.
type RechargeProductUpdate struct {
	config
	hooks    []Hook
	mutation *RechargeProductMutation
}

// Where appends a list predicates to the RechargeProductUpdate builder.
func (_u *RechargeProductUpdate) Where(ps ...predicate.RechargeProduct) *RechargeProductUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *RechargeProductUpdate) SetName(v string) *RechargeProductUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RechargeProductUpdate) SetNillableName(v *string) *RechargeProductUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RechargeProductUpdate) SetAmount(v float64) *RechargeProductUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RechargeProductUpdate) SetNillableAmount(v *float64) *RechargeProductUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *RechargeProductUpdate) AddAmount(v float64) *RechargeProductUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalance sets the "balance" field.
func (_u *RechargeProductUpdate) SetBalance(v float64) *RechargeProductUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *RechargeProductUpdate) SetNillableBalance(v *float64) *RechargeProductUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *RechargeProductUpdate) AddBalance(v float64) *RechargeProductUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetBonusBalance sets the "bonus_balance" field.
func (_u *RechargeProductUpdate) SetBonusBalance(v float64) *RechargeProductUpdate {
	_u.mutation.ResetBonusBalance()
	_u.mutation.SetBonusBalance(v)
	return _u
}

// SetNillableBonusBalance sets the "bonus_balance" field if the given value is not nil.
func (_u *RechargeProductUpdate) SetNillableBonusBalance(v *float64) *RechargeProductUpdate {
	if v != nil {
		_u.SetBonusBalance(*v)
	}
	return _u
}

// AddBonusBalance adds value to the "bonus_balance" field.
func (_u *RechargeProductUpdate) AddBonusBalance(v float64) *RechargeProductUpdate {
	_u.mutation.AddBonusBalance(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *RechargeProductUpdate) SetDescription(v string) *RechargeProductUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RechargeProductUpdate) SetNillableDescription(v *string) *RechargeProductUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *RechargeProductUpdate) SetSortOrder(v int) *RechargeProductUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *RechargeProductUpdate) SetNillableSortOrder(v *int) *RechargeProductUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *RechargeProductUpdate) AddSortOrder(v int) *RechargeProductUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetIsHot sets the "is_hot" field.
func (_u *RechargeProductUpdate) SetIsHot(v bool) *RechargeProductUpdate {
	_u.mutation.SetIsHot(v)
	return _u
}

// SetNillableIsHot sets the "is_hot" field if the given value is not nil.
func (_u *RechargeProductUpdate) SetNillableIsHot(v *bool) *RechargeProductUpdate {
	if v != nil {
		_u.SetIsHot(*v)
	}
	return _u
}

// SetDiscountLabel sets the "discount_label" field.
func (_u *RechargeProductUpdate) SetDiscountLabel(v string) *RechargeProductUpdate {
	_u.mutation.SetDiscountLabel(v)
	return _u
}

// SetNillableDiscountLabel sets the "discount_label" field if the given value is not nil.
func (_u *RechargeProductUpdate) SetNillableDiscountLabel(v *string) *RechargeProductUpdate {
	if v != nil {
		_u.SetDiscountLabel(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RechargeProductUpdate) SetStatus(v string) *RechargeProductUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RechargeProductUpdate) SetNillableStatus(v *string) *RechargeProductUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RechargeProductUpdate) SetCreatedAt(v time.Time) *RechargeProductUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RechargeProductUpdate) SetNillableCreatedAt(v *time.Time) *RechargeProductUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RechargeProductUpdate) SetUpdatedAt(v time.Time) *RechargeProductUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RechargeProductUpdate) SetNillableUpdatedAt(v *time.Time) *RechargeProductUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddOrderIDs adds the "orders" edge to the Order entity by IDs.
func (_u *RechargeProductUpdate) AddOrderIDs(ids ...int64) *RechargeProductUpdate {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the Order entity.
func (_u *RechargeProductUpdate) AddOrders(v ...*Order) *RechargeProductUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// Mutation returns the RechargeProductMutation object of the builder.
func (_u *RechargeProductUpdate) Mutation() *RechargeProductMutation {
	return _u.mutation
}

// ClearOrders clears all "orders" edges to the Order entity.
func (_u *RechargeProductUpdate) ClearOrders() *RechargeProductUpdate {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to Order entities by IDs.
func (_u *RechargeProductUpdate) RemoveOrderIDs(ids ...int64) *RechargeProductUpdate {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to Order entities.
func (_u *RechargeProductUpdate) RemoveOrders(v ...*Order) *RechargeProductUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RechargeProductUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RechargeProductUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RechargeProductUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RechargeProductUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RechargeProductUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := rechargeproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RechargeProduct.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DiscountLabel(); ok {
		if err := rechargeproduct.DiscountLabelValidator(v); err != nil {
			return &ValidationError{Name: "discount_label", err: fmt.Errorf(`ent: validator failed for field "RechargeProduct.discount_label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rechargeproduct.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RechargeProduct.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RechargeProductUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rechargeproduct.Table, rechargeproduct.Columns, sqlgraph.NewFieldSpec(rechargeproduct.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rechargeproduct.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(rechargeproduct.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(rechargeproduct.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(rechargeproduct.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(rechargeproduct.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BonusBalance(); ok {
		_spec.SetField(rechargeproduct.FieldBonusBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBonusBalance(); ok {
		_spec.AddField(rechargeproduct.FieldBonusBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rechargeproduct.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(rechargeproduct.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(rechargeproduct.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsHot(); ok {
		_spec.SetField(rechargeproduct.FieldIsHot, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DiscountLabel(); ok {
		_spec.SetField(rechargeproduct.FieldDiscountLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rechargeproduct.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(rechargeproduct.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargeproduct.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeproduct.OrdersTable,
			Columns: []string{rechargeproduct.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeproduct.OrdersTable,
			Columns: []string{rechargeproduct.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeproduct.OrdersTable,
			Columns: []string{rechargeproduct.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rechargeproduct.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RechargeProductUpdateOne is the builder for updating a single RechargeProduct entity.
type RechargeProductUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RechargeProductMutation
}

// SetName sets the "name" field.
func (_u *RechargeProductUpdateOne) SetName(v string) *RechargeProductUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RechargeProductUpdateOne) SetNillableName(v *string) *RechargeProductUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAmount sets the "amount" field.
func (_u *RechargeProductUpdateOne) SetAmount(v float64) *RechargeProductUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *RechargeProductUpdateOne) SetNillableAmount(v *float64) *RechargeProductUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *RechargeProductUpdateOne) AddAmount(v float64) *RechargeProductUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetBalance sets the "balance" field.
func (_u *RechargeProductUpdateOne) SetBalance(v float64) *RechargeProductUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *RechargeProductUpdateOne) SetNillableBalance(v *float64) *RechargeProductUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *RechargeProductUpdateOne) AddBalance(v float64) *RechargeProductUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetBonusBalance sets the "bonus_balance" field.
func (_u *RechargeProductUpdateOne) SetBonusBalance(v float64) *RechargeProductUpdateOne {
	_u.mutation.ResetBonusBalance()
	_u.mutation.SetBonusBalance(v)
	return _u
}

// SetNillableBonusBalance sets the "bonus_balance" field if the given value is not nil.
func (_u *RechargeProductUpdateOne) SetNillableBonusBalance(v *float64) *RechargeProductUpdateOne {
	if v != nil {
		_u.SetBonusBalance(*v)
	}
	return _u
}

// AddBonusBalance adds value to the "bonus_balance" field.
func (_u *RechargeProductUpdateOne) AddBonusBalance(v float64) *RechargeProductUpdateOne {
	_u.mutation.AddBonusBalance(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *RechargeProductUpdateOne) SetDescription(v string) *RechargeProductUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RechargeProductUpdateOne) SetNillableDescription(v *string) *RechargeProductUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *RechargeProductUpdateOne) SetSortOrder(v int) *RechargeProductUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *RechargeProductUpdateOne) SetNillableSortOrder(v *int) *RechargeProductUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *RechargeProductUpdateOne) AddSortOrder(v int) *RechargeProductUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetIsHot sets the "is_hot" field.
func (_u *RechargeProductUpdateOne) SetIsHot(v bool) *RechargeProductUpdateOne {
	_u.mutation.SetIsHot(v)
	return _u
}

// SetNillableIsHot sets the "is_hot" field if the given value is not nil.
func (_u *RechargeProductUpdateOne) SetNillableIsHot(v *bool) *RechargeProductUpdateOne {
	if v != nil {
		_u.SetIsHot(*v)
	}
	return _u
}

// SetDiscountLabel sets the "discount_label" field.
func (_u *RechargeProductUpdateOne) SetDiscountLabel(v string) *RechargeProductUpdateOne {
	_u.mutation.SetDiscountLabel(v)
	return _u
}

// SetNillableDiscountLabel sets the "discount_label" field if the given value is not nil.
func (_u *RechargeProductUpdateOne) SetNillableDiscountLabel(v *string) *RechargeProductUpdateOne {
	if v != nil {
		_u.SetDiscountLabel(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RechargeProductUpdateOne) SetStatus(v string) *RechargeProductUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RechargeProductUpdateOne) SetNillableStatus(v *string) *RechargeProductUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *RechargeProductUpdateOne) SetCreatedAt(v time.Time) *RechargeProductUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *RechargeProductUpdateOne) SetNillableCreatedAt(v *time.Time) *RechargeProductUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RechargeProductUpdateOne) SetUpdatedAt(v time.Time) *RechargeProductUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *RechargeProductUpdateOne) SetNillableUpdatedAt(v *time.Time) *RechargeProductUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// AddOrderIDs adds the "orders" edge to the Order entity by IDs.
func (_u *RechargeProductUpdateOne) AddOrderIDs(ids ...int64) *RechargeProductUpdateOne {
	_u.mutation.AddOrderIDs(ids...)
	return _u
}

// AddOrders adds the "orders" edges to the Order entity.
func (_u *RechargeProductUpdateOne) AddOrders(v ...*Order) *RechargeProductUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddOrderIDs(ids...)
}

// Mutation returns the RechargeProductMutation object of the builder.
func (_u *RechargeProductUpdateOne) Mutation() *RechargeProductMutation {
	return _u.mutation
}

// ClearOrders clears all "orders" edges to the Order entity.
func (_u *RechargeProductUpdateOne) ClearOrders() *RechargeProductUpdateOne {
	_u.mutation.ClearOrders()
	return _u
}

// RemoveOrderIDs removes the "orders" edge to Order entities by IDs.
func (_u *RechargeProductUpdateOne) RemoveOrderIDs(ids ...int64) *RechargeProductUpdateOne {
	_u.mutation.RemoveOrderIDs(ids...)
	return _u
}

// RemoveOrders removes "orders" edges to Order entities.
func (_u *RechargeProductUpdateOne) RemoveOrders(v ...*Order) *RechargeProductUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveOrderIDs(ids...)
}

// Where appends a list predicates to the RechargeProductUpdate builder.
func (_u *RechargeProductUpdateOne) Where(ps ...predicate.RechargeProduct) *RechargeProductUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RechargeProductUpdateOne) Select(field string, fields ...string) *RechargeProductUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RechargeProduct entity.
func (_u *RechargeProductUpdateOne) Save(ctx context.Context) (*RechargeProduct, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RechargeProductUpdateOne) SaveX(ctx context.Context) *RechargeProduct {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RechargeProductUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RechargeProductUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RechargeProductUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := rechargeproduct.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RechargeProduct.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DiscountLabel(); ok {
		if err := rechargeproduct.DiscountLabelValidator(v); err != nil {
			return &ValidationError{Name: "discount_label", err: fmt.Errorf(`ent: validator failed for field "RechargeProduct.discount_label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := rechargeproduct.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RechargeProduct.status": %w`, err)}
		}
	}
	return nil
}

func (_u *RechargeProductUpdateOne) sqlSave(ctx context.Context) (_node *RechargeProduct, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rechargeproduct.Table, rechargeproduct.Columns, sqlgraph.NewFieldSpec(rechargeproduct.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RechargeProduct.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rechargeproduct.FieldID)
		for _, f := range fields {
			if !rechargeproduct.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rechargeproduct.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(rechargeproduct.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(rechargeproduct.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(rechargeproduct.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(rechargeproduct.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(rechargeproduct.FieldBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BonusBalance(); ok {
		_spec.SetField(rechargeproduct.FieldBonusBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBonusBalance(); ok {
		_spec.AddField(rechargeproduct.FieldBonusBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(rechargeproduct.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(rechargeproduct.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(rechargeproduct.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsHot(); ok {
		_spec.SetField(rechargeproduct.FieldIsHot, field.TypeBool, value)
	}
	if value, ok := _u.mutation.DiscountLabel(); ok {
		_spec.SetField(rechargeproduct.FieldDiscountLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(rechargeproduct.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(rechargeproduct.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargeproduct.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeproduct.OrdersTable,
			Columns: []string{rechargeproduct.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedOrdersIDs(); len(nodes) > 0 && !_u.mutation.OrdersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeproduct.OrdersTable,
			Columns: []string{rechargeproduct.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   rechargeproduct.OrdersTable,
			Columns: []string{rechargeproduct.OrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RechargeProduct{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rechargeproduct.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
